### ISSUE TITLE
Error at Producing Inputs for LM 

### ISSUE THREAD

**Issue by skarakulak** [aetting/lm-diagnostics#1]
I have run the command to produce inputs for LM as below:
```
python prediction_accuracy_tests.py \
  --preddir <location of modelpreds-<testname>-<modelname>> \
  --resultsdir datasets_output/ \
  --models <names of models to be tested, e.g., bert-base-uncased bert-large-uncased> \
  --k_values <list of k values to be tested, e.g., 1 5> \
  --role_stim datasets/ROLE-88/ROLE-88.tsv \
  --negnat_stim datasets/NEG-88/NEG-88-NAT.tsv \
  --negsimp_stim datasets/NEG-88/NEG-88-SIMP.tsv \
  --cprag_stim datasets/CPRAG-34/CPRAG-34.tsv
```

However, I'm getting the error below using Python 3.7.5:
```Traceback (most recent call last):
  File "proc_datasets.py", line 176, in <module>
    out.write('\n'.join([c.encode('utf-8') for c in inputlist]))
TypeError: sequence item 0: expected str instance, bytes found
```
Since I didn't have the output of this script to confirm what I should be expecting to produce, I wanted to report the issue before making any changes to my code. Also can I ask the versions of the python libraries that are used?

Best,

**Comment by aetting** [comment]
Thanks for pointing out this issue. I will fix the code shortly to be compatible with Python 3, but in the next week or so before I get around to that, the quickest fix might be just to run it in Python 2.7 (or go ahead and switch up the relevant write lines, which are hopefully the only issue). Which libraries are you wondering about?

**Comment by skarakulak** [comment]
Thank you, I will run it with Python 2.7. 
About the libraries, I just wanted to reproduce the results and experiment with couple of things. It would just make it easier and help for reproducibility purposes if you there was a environment file that specified the versions of the libraries that were used in the experiments.

**Comment by aetting** [comment]
I've updated the code to be run with Python 3 (and added a 'versions.txt' with library versions used). I'll close this issue for now, but let me know if you encounter any further issues.
